// <auto-generated />
using Beca.KeyboardShop.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beca.KeyboardShop.Migrations
{
    [DbContext(typeof(KeyboardShopDbContext))]
    [Migration("20221121111121_SeedNewKeyboard")]
    partial class SeedNewKeyboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Beca.KeyboardShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Slim"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mechanical"
                        });
                });

            modelBuilder.Entity("Beca.KeyboardShop.Entities.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Keyboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A minimalist keyboard with a US QWERTY key layout for Mac computers.",
                            Name = "Logitech MX",
                            Price = 149.99000000000001
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "An ergonomic and sophisticated keyboard that will give you a great gaming experience.",
                            Name = "Forgeon Clutch 60% Switch Brown",
                            Price = 99.989999999999995
                        });
                });

            modelBuilder.Entity("Beca.KeyboardShop.Entities.Keyboard", b =>
                {
                    b.HasOne("Beca.KeyboardShop.Entities.Category", "Category")
                        .WithMany("Keyboards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Beca.KeyboardShop.Entities.Category", b =>
                {
                    b.Navigation("Keyboards");
                });
#pragma warning restore 612, 618
        }
    }
}
